<?php
/**
* @package SP Page Builder
* @author JoomShaper http://www.joomshaper.com
* @copyright Copyright (c) 2010 - 2020 JoomShaper
* @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or later
*/
//no direct accees
defined ('_JEXEC') or die ('Restricted access');

$icon_list =  array(
	'linearicons-home',
	'linearicons-home2',
	'linearicons-home3',
	'linearicons-home4',
	'linearicons-home5',
	'linearicons-home6',
	'linearicons-bathtub',
	'linearicons-toothbrush',
	'linearicons-bed',
	'linearicons-couch',
	'linearicons-chair',
	'linearicons-city',
	'linearicons-apartment',
	'linearicons-pencil',
	'linearicons-pencil2',
	'linearicons-pen',
	'linearicons-pencil3',
	'linearicons-eraser',
	'linearicons-pencil4',
	'linearicons-pencil5',
	'linearicons-feather',
	'linearicons-feather2',
	'linearicons-feather3',
	'linearicons-pen2',
	'linearicons-pen-add',
	'linearicons-pen-remove',
	'linearicons-vector',
	'linearicons-pen3',
	'linearicons-blog',
	'linearicons-brush',
	'linearicons-brush2',
	'linearicons-spray',
	'linearicons-paint-roller',
	'linearicons-stamp',
	'linearicons-tape',
	'linearicons-desk-tape',
	'linearicons-texture',
	'linearicons-eye-dropper',
	'linearicons-palette',
	'linearicons-color-sampler',
	'linearicons-bucket',
	'linearicons-gradient',
	'linearicons-gradient2',
	'linearicons-magic-wand',
	'linearicons-magnet',
	'linearicons-pencil-ruler',
	'linearicons-pencil-ruler2',
	'linearicons-compass',
	'linearicons-aim',
	'linearicons-gun',
	'linearicons-bottle',
	'linearicons-drop',
	'linearicons-drop-crossed',
	'linearicons-drop2',
	'linearicons-snow',
	'linearicons-snow2',
	'linearicons-fire',
	'linearicons-lighter',
	'linearicons-knife',
	'linearicons-dagger',
	'linearicons-tissue',
	'linearicons-toilet-paper',
	'linearicons-poop',
	'linearicons-umbrella',
	'linearicons-umbrella2',
	'linearicons-rain',
	'linearicons-tornado',
	'linearicons-wind',
	'linearicons-fan',
	'linearicons-contrast',
	'linearicons-sun-small',
	'linearicons-sun',
	'linearicons-sun2',
	'linearicons-moon',
	'linearicons-cloud',
	'linearicons-cloud-upload',
	'linearicons-cloud-download',
	'linearicons-cloud-rain',
	'linearicons-cloud-hailstones',
	'linearicons-cloud-snow',
	'linearicons-cloud-windy',
	'linearicons-sun-wind',
	'linearicons-cloud-fog',
	'linearicons-cloud-sun',
	'linearicons-cloud-lightning',
	'linearicons-cloud-sync',
	'linearicons-cloud-lock',
	'linearicons-cloud-gear',
	'linearicons-cloud-alert',
	'linearicons-cloud-check',
	'linearicons-cloud-cross',
	'linearicons-cloud-crossed',
	'linearicons-cloud-database',
	'linearicons-database',
	'linearicons-database-add',
	'linearicons-database-remove',
	'linearicons-database-lock',
	'linearicons-database-refresh',
	'linearicons-database-check',
	'linearicons-database-history',
	'linearicons-database-upload',
	'linearicons-database-download',
	'linearicons-server',
	'linearicons-shield',
	'linearicons-shield-check',
	'linearicons-shield-alert',
	'linearicons-shield-cross',
	'linearicons-lock',
	'linearicons-rotation-lock',
	'linearicons-unlock',
	'linearicons-key',
	'linearicons-key-hole',
	'linearicons-toggle-off',
	'linearicons-toggle-on',
	'linearicons-cog',
	'linearicons-cog2',
	'linearicons-wrench',
	'linearicons-screwdriver',
	'linearicons-hammer-wrench',
	'linearicons-hammer',
	'linearicons-saw',
	'linearicons-axe',
	'linearicons-axe2',
	'linearicons-shovel',
	'linearicons-pickaxe',
	'linearicons-factory',
	'linearicons-factory2',
	'linearicons-recycle',
	'linearicons-trash',
	'linearicons-trash2',
	'linearicons-trash3',
	'linearicons-broom',
	'linearicons-game',
	'linearicons-gamepad',
	'linearicons-joystick',
	'linearicons-dice',
	'linearicons-spades',
	'linearicons-diamonds',
	'linearicons-clubs',
	'linearicons-hearts',
	'linearicons-heart',
	'linearicons-star',
	'linearicons-star-half',
	'linearicons-star-empty',
	'linearicons-flag',
	'linearicons-flag2',
	'linearicons-flag3',
	'linearicons-mailbox-full',
	'linearicons-mailbox-empty',
	'linearicons-at-sign',
	'linearicons-envelope',
	'linearicons-envelope-open',
	'linearicons-paperclip',
	'linearicons-paper-plane',
	'linearicons-reply',
	'linearicons-reply-all',
	'linearicons-inbox',
	'linearicons-inbox2',
	'linearicons-outbox',
	'linearicons-box',
	'linearicons-archive',
	'linearicons-archive2',
	'linearicons-drawers',
	'linearicons-drawers2',
	'linearicons-drawers3',
	'linearicons-eye',
	'linearicons-eye-crossed',
	'linearicons-eye-plus',
	'linearicons-eye-minus',
	'linearicons-binoculars',
	'linearicons-binoculars2',
	'linearicons-hdd',
	'linearicons-hdd-down',
	'linearicons-hdd-up',
	'linearicons-floppy-disk',
	'linearicons-disc',
	'linearicons-tape2',
	'linearicons-printer',
	'linearicons-shredder',
	'linearicons-file-empty',
	'linearicons-file-add',
	'linearicons-file-check',
	'linearicons-file-lock',
	'linearicons-files',
	'linearicons-copy',
	'linearicons-compare',
	'linearicons-folder',
	'linearicons-folder-search',
	'linearicons-folder-plus',
	'linearicons-folder-minus',
	'linearicons-folder-download',
	'linearicons-folder-upload',
	'linearicons-folder-star',
	'linearicons-folder-heart',
	'linearicons-folder-user',
	'linearicons-folder-shared',
	'linearicons-folder-music',
	'linearicons-folder-picture',
	'linearicons-folder-film',
	'linearicons-scissors',
	'linearicons-paste',
	'linearicons-clipboard-empty',
	'linearicons-clipboard-pencil',
	'linearicons-clipboard-text',
	'linearicons-clipboard-check',
	'linearicons-clipboard-down',
	'linearicons-clipboard-left',
	'linearicons-clipboard-alert',
	'linearicons-clipboard-user',
	'linearicons-register',
	'linearicons-enter',
	'linearicons-exit',
	'linearicons-papers',
	'linearicons-news',
	'linearicons-reading',
	'linearicons-typewriter',
	'linearicons-document',
	'linearicons-document2',
	'linearicons-graduation-hat',
	'linearicons-license',
	'linearicons-license2',
	'linearicons-medal-empty',
	'linearicons-medal-first',
	'linearicons-medal-second',
	'linearicons-medal-third',
	'linearicons-podium',
	'linearicons-trophy',
	'linearicons-trophy2',
	'linearicons-music-note',
	'linearicons-music-note2',
	'linearicons-music-note3',
	'linearicons-playlist',
	'linearicons-playlist-add',
	'linearicons-guitar',
	'linearicons-trumpet',
	'linearicons-album',
	'linearicons-shuffle',
	'linearicons-repeat-one',
	'linearicons-repeat',
	'linearicons-headphones',
	'linearicons-headset',
	'linearicons-loudspeaker',
	'linearicons-equalizer',
	'linearicons-theater',
	'linearicons-3d-glasses',
	'linearicons-ticket',
	'linearicons-presentation',
	'linearicons-play',
	'linearicons-film-play',
	'linearicons-clapboard-play',
	'linearicons-media',
	'linearicons-film',
	'linearicons-film2',
	'linearicons-surveillance',
	'linearicons-surveillance2',
	'linearicons-camera',
	'linearicons-camera-crossed',
	'linearicons-camera-play',
	'linearicons-time-lapse',
	'linearicons-record',
	'linearicons-camera2',
	'linearicons-camera-flip',
	'linearicons-panorama',
	'linearicons-time-lapse2',
	'linearicons-shutter',
	'linearicons-shutter2',
	'linearicons-face-detection',
	'linearicons-flare',
	'linearicons-convex',
	'linearicons-concave',
	'linearicons-picture',
	'linearicons-picture2',
	'linearicons-picture3',
	'linearicons-pictures',
	'linearicons-book',
	'linearicons-audio-book',
	'linearicons-book2',
	'linearicons-bookmark',
	'linearicons-bookmark2',
	'linearicons-label',
	'linearicons-library',
	'linearicons-library2',
	'linearicons-contacts',
	'linearicons-profile',
	'linearicons-portrait',
	'linearicons-portrait2',
	'linearicons-user',
	'linearicons-user-plus',
	'linearicons-user-minus',
	'linearicons-user-lock',
	'linearicons-users',
	'linearicons-users2',
	'linearicons-users-plus',
	'linearicons-users-minus',
	'linearicons-group-work',
	'linearicons-woman',
	'linearicons-man',
	'linearicons-baby',
	'linearicons-baby2',
	'linearicons-baby3',
	'linearicons-baby-bottle',
	'linearicons-walk',
	'linearicons-hand-waving',
	'linearicons-jump',
	'linearicons-run',
	'linearicons-woman2',
	'linearicons-man2',
	'linearicons-man-woman',
	'linearicons-height',
	'linearicons-weight',
	'linearicons-scale',
	'linearicons-button',
	'linearicons-bow-tie',
	'linearicons-tie',
	'linearicons-socks',
	'linearicons-shoe',
	'linearicons-shoes',
	'linearicons-hat',
	'linearicons-pants',
	'linearicons-shorts',
	'linearicons-flip-flops',
	'linearicons-shirt',
	'linearicons-hanger',
	'linearicons-laundry',
	'linearicons-store',
	'linearicons-haircut',
	'linearicons-store-24',
	'linearicons-barcode',
	'linearicons-barcode2',
	'linearicons-barcode3',
	'linearicons-cashier',
	'linearicons-bag',
	'linearicons-bag2',
	'linearicons-cart',
	'linearicons-cart-empty',
	'linearicons-cart-full',
	'linearicons-cart-plus',
	'linearicons-cart-plus2',
	'linearicons-cart-add',
	'linearicons-cart-remove',
	'linearicons-cart-exchange',
	'linearicons-tag',
	'linearicons-tags',
	'linearicons-receipt',
	'linearicons-wallet',
	'linearicons-credit-card',
	'linearicons-cash-dollar',
	'linearicons-cash-euro',
	'linearicons-cash-pound',
	'linearicons-cash-yen',
	'linearicons-bag-dollar',
	'linearicons-bag-euro',
	'linearicons-bag-pound',
	'linearicons-bag-yen',
	'linearicons-coin-dollar',
	'linearicons-coin-euro',
	'linearicons-coin-pound',
	'linearicons-coin-yen',
	'linearicons-calculator',
	'linearicons-calculator2',
	'linearicons-abacus',
	'linearicons-vault',
	'linearicons-telephone',
	'linearicons-phone-lock',
	'linearicons-phone-wave',
	'linearicons-phone-pause',
	'linearicons-phone-outgoing',
	'linearicons-phone-incoming',
	'linearicons-phone-in-out',
	'linearicons-phone-error',
	'linearicons-phone-sip',
	'linearicons-phone-plus',
	'linearicons-phone-minus',
	'linearicons-voicemail',
	'linearicons-dial',
	'linearicons-telephone2',
	'linearicons-pushpin',
	'linearicons-pushpin2',
	'linearicons-map-marker',
	'linearicons-map-marker-user',
	'linearicons-map-marker-down',
	'linearicons-map-marker-check',
	'linearicons-map-marker-crossed',
	'linearicons-radar',
	'linearicons-compass2',
	'linearicons-map',
	'linearicons-map2',
	'linearicons-location',
	'linearicons-road-sign',
	'linearicons-calendar-empty',
	'linearicons-calendar-check',
	'linearicons-calendar-cross',
	'linearicons-calendar-31',
	'linearicons-calendar-full',
	'linearicons-calendar-insert',
	'linearicons-calendar-text',
	'linearicons-calendar-user',
	'linearicons-mouse',
	'linearicons-mouse-left',
	'linearicons-mouse-right',
	'linearicons-mouse-both',
	'linearicons-keyboard',
	'linearicons-keyboard-up',
	'linearicons-keyboard-down',
	'linearicons-delete',
	'linearicons-spell-check',
	'linearicons-escape',
	'linearicons-enter2',
	'linearicons-screen',
	'linearicons-aspect-ratio',
	'linearicons-signal',
	'linearicons-signal-lock',
	'linearicons-signal-80',
	'linearicons-signal-60',
	'linearicons-signal-40',
	'linearicons-signal-20',
	'linearicons-signal-0',
	'linearicons-signal-blocked',
	'linearicons-sim',
	'linearicons-flash-memory',
	'linearicons-usb-drive',
	'linearicons-phone',
	'linearicons-smartphone',
	'linearicons-smartphone-notification',
	'linearicons-smartphone-vibration',
	'linearicons-smartphone-embed',
	'linearicons-smartphone-waves',
	'linearicons-tablet',
	'linearicons-tablet2',
	'linearicons-laptop',
	'linearicons-laptop-phone',
	'linearicons-desktop',
	'linearicons-launch',
	'linearicons-new-tab',
	'linearicons-window',
	'linearicons-cable',
	'linearicons-cable2',
	'linearicons-tv',
	'linearicons-radio',
	'linearicons-remote-control',
	'linearicons-power-switch',
	'linearicons-power',
	'linearicons-power-crossed',
	'linearicons-flash-auto',
	'linearicons-lamp',
	'linearicons-flashlight',
	'linearicons-lampshade',
	'linearicons-cord',
	'linearicons-outlet',
	'linearicons-battery-power',
	'linearicons-battery-empty',
	'linearicons-battery-alert',
	'linearicons-battery-error',
	'linearicons-battery-low1',
	'linearicons-battery-low2',
	'linearicons-battery-low3',
	'linearicons-battery-mid1',
	'linearicons-battery-mid2',
	'linearicons-battery-mid3',
	'linearicons-battery-full',
	'linearicons-battery-charging',
	'linearicons-battery-charging2',
	'linearicons-battery-charging3',
	'linearicons-battery-charging4',
	'linearicons-battery-charging5',
	'linearicons-battery-charging6',
	'linearicons-battery-charging7',
	'linearicons-chip',
	'linearicons-chip-x64',
	'linearicons-chip-x86',
	'linearicons-bubble',
	'linearicons-bubbles',
	'linearicons-bubble-dots',
	'linearicons-bubble-alert',
	'linearicons-bubble-question',
	'linearicons-bubble-text',
	'linearicons-bubble-pencil',
	'linearicons-bubble-picture',
	'linearicons-bubble-video',
	'linearicons-bubble-user',
	'linearicons-bubble-quote',
	'linearicons-bubble-heart',
	'linearicons-bubble-emoticon',
	'linearicons-bubble-attachment',
	'linearicons-phone-bubble',
	'linearicons-quote-open',
	'linearicons-quote-close',
	'linearicons-dna',
	'linearicons-heart-pulse',
	'linearicons-pulse',
	'linearicons-syringe',
	'linearicons-pills',
	'linearicons-first-aid',
	'linearicons-lifebuoy',
	'linearicons-bandage',
	'linearicons-bandages',
	'linearicons-thermometer',
	'linearicons-microscope',
	'linearicons-brain',
	'linearicons-beaker',
	'linearicons-skull',
	'linearicons-bone',
	'linearicons-construction',
	'linearicons-construction-cone',
	'linearicons-pie-chart',
	'linearicons-pie-chart2',
	'linearicons-graph',
	'linearicons-chart-growth',
	'linearicons-chart-bars',
	'linearicons-chart-settings',
	'linearicons-cake',
	'linearicons-gift',
	'linearicons-balloon',
	'linearicons-rank',
	'linearicons-rank2',
	'linearicons-rank3',
	'linearicons-crown',
	'linearicons-lotus',
	'linearicons-diamond',
	'linearicons-diamond2',
	'linearicons-diamond3',
	'linearicons-diamond4',
	'linearicons-linearicons',
	'linearicons-teacup',
	'linearicons-teapot',
	'linearicons-glass',
	'linearicons-bottle2',
	'linearicons-glass-cocktail',
	'linearicons-glass2',
	'linearicons-dinner',
	'linearicons-dinner2',
	'linearicons-chef',
	'linearicons-scale2',
	'linearicons-egg',
	'linearicons-egg2',
	'linearicons-eggs',
	'linearicons-platter',
	'linearicons-steak',
	'linearicons-hamburger',
	'linearicons-hotdog',
	'linearicons-pizza',
	'linearicons-sausage',
	'linearicons-chicken',
	'linearicons-fish',
	'linearicons-carrot',
	'linearicons-cheese',
	'linearicons-bread',
	'linearicons-ice-cream',
	'linearicons-ice-cream2',
	'linearicons-candy',
	'linearicons-lollipop',
	'linearicons-coffee-bean',
	'linearicons-coffee-cup',
	'linearicons-cherry',
	'linearicons-grapes',
	'linearicons-citrus',
	'linearicons-apple',
	'linearicons-leaf',
	'linearicons-landscape',
	'linearicons-pine-tree',
	'linearicons-tree',
	'linearicons-cactus',
	'linearicons-paw',
	'linearicons-footprint',
	'linearicons-speed-slow',
	'linearicons-speed-medium',
	'linearicons-speed-fast',
	'linearicons-rocket',
	'linearicons-hammer2',
	'linearicons-balance',
	'linearicons-briefcase',
	'linearicons-luggage-weight',
	'linearicons-dolly',
	'linearicons-plane',
	'linearicons-plane-crossed',
	'linearicons-helicopter',
	'linearicons-traffic-lights',
	'linearicons-siren',
	'linearicons-road',
	'linearicons-engine',
	'linearicons-oil-pressure',
	'linearicons-coolant-temperature',
	'linearicons-car-battery',
	'linearicons-gas',
	'linearicons-gallon',
	'linearicons-transmission',
	'linearicons-car',
	'linearicons-car-wash',
	'linearicons-car-wash2',
	'linearicons-bus',
	'linearicons-bus2',
	'linearicons-car2',
	'linearicons-parking',
	'linearicons-car-lock',
	'linearicons-taxi',
	'linearicons-car-siren',
	'linearicons-car-wash3',
	'linearicons-car-wash4',
	'linearicons-ambulance',
	'linearicons-truck',
	'linearicons-trailer',
	'linearicons-scale-truck',
	'linearicons-train',
	'linearicons-ship',
	'linearicons-ship2',
	'linearicons-anchor',
	'linearicons-boat',
	'linearicons-bicycle',
	'linearicons-bicycle2',
	'linearicons-dumbbell',
	'linearicons-bench-press',
	'linearicons-swim',
	'linearicons-football',
	'linearicons-baseball-bat',
	'linearicons-baseball',
	'linearicons-tennis',
	'linearicons-tennis2',
	'linearicons-ping-pong',
	'linearicons-hockey',
	'linearicons-8ball',
	'linearicons-bowling',
	'linearicons-bowling-pins',
	'linearicons-golf',
	'linearicons-golf2',
	'linearicons-archery',
	'linearicons-slingshot',
	'linearicons-soccer',
	'linearicons-basketball',
	'linearicons-cube',
	'linearicons-3d-rotate',
	'linearicons-puzzle',
	'linearicons-glasses',
	'linearicons-glasses2',
	'linearicons-accessibility',
	'linearicons-wheelchair',
	'linearicons-wall',
	'linearicons-fence',
	'linearicons-wall2',
	'linearicons-icons',
	'linearicons-resize-handle',
	'linearicons-icons2',
	'linearicons-select',
	'linearicons-select2',
	'linearicons-site-map',
	'linearicons-earth',
	'linearicons-earth-lock',
	'linearicons-network',
	'linearicons-network-lock',
	'linearicons-planet',
	'linearicons-happy',
	'linearicons-smile',
	'linearicons-grin',
	'linearicons-tongue',
	'linearicons-sad',
	'linearicons-wink',
	'linearicons-dream',
	'linearicons-shocked',
	'linearicons-shocked2',
	'linearicons-tongue2',
	'linearicons-neutral',
	'linearicons-happy-grin',
	'linearicons-cool',
	'linearicons-mad',
	'linearicons-grin-evil',
	'linearicons-evil',
	'linearicons-wow',
	'linearicons-annoyed',
	'linearicons-wondering',
	'linearicons-confused',
	'linearicons-zipped',
	'linearicons-grumpy',
	'linearicons-mustache',
	'linearicons-tombstone-hipster',
	'linearicons-tombstone',
	'linearicons-ghost',
	'linearicons-ghost-hipster',
	'linearicons-halloween',
	'linearicons-christmas',
	'linearicons-easter-egg',
	'linearicons-mustache2',
	'linearicons-mustache-glasses',
	'linearicons-pipe',
	'linearicons-alarm',
	'linearicons-alarm-add',
	'linearicons-alarm-snooze',
	'linearicons-alarm-ringing',
	'linearicons-bullhorn',
	'linearicons-hearing',
	'linearicons-volume-high',
	'linearicons-volume-medium',
	'linearicons-volume-low',
	'linearicons-volume',
	'linearicons-mute',
	'linearicons-lan',
	'linearicons-lan2',
	'linearicons-wifi',
	'linearicons-wifi-lock',
	'linearicons-wifi-blocked',
	'linearicons-wifi-mid',
	'linearicons-wifi-low',
	'linearicons-wifi-low2',
	'linearicons-wifi-alert',
	'linearicons-wifi-alert-mid',
	'linearicons-wifi-alert-low',
	'linearicons-wifi-alert-low2',
	'linearicons-stream',
	'linearicons-stream-check',
	'linearicons-stream-error',
	'linearicons-stream-alert',
	'linearicons-communication',
	'linearicons-communication-crossed',
	'linearicons-broadcast',
	'linearicons-antenna',
	'linearicons-satellite',
	'linearicons-satellite2',
	'linearicons-mic',
	'linearicons-mic-mute',
	'linearicons-mic2',
	'linearicons-spotlights',
	'linearicons-hourglass',
	'linearicons-loading',
	'linearicons-loading2',
	'linearicons-loading3',
	'linearicons-refresh',
	'linearicons-refresh2',
	'linearicons-undo',
	'linearicons-redo',
	'linearicons-jump2',
	'linearicons-undo2',
	'linearicons-redo2',
	'linearicons-sync',
	'linearicons-repeat-one2',
	'linearicons-sync-crossed',
	'linearicons-sync2',
	'linearicons-repeat-one3',
	'linearicons-sync-crossed2',
	'linearicons-return',
	'linearicons-return2',
	'linearicons-refund',
	'linearicons-history',
	'linearicons-history2',
	'linearicons-self-timer',
	'linearicons-clock',
	'linearicons-clock2',
	'linearicons-clock3',
	'linearicons-watch',
	'linearicons-alarm2',
	'linearicons-alarm-add2',
	'linearicons-alarm-remove',
	'linearicons-alarm-check',
	'linearicons-alarm-error',
	'linearicons-timer',
	'linearicons-timer-crossed',
	'linearicons-timer2',
	'linearicons-timer-crossed2',
	'linearicons-download',
	'linearicons-upload',
	'linearicons-download2',
	'linearicons-upload2',
	'linearicons-enter-up',
	'linearicons-enter-down',
	'linearicons-enter-left',
	'linearicons-enter-right',
	'linearicons-exit-up',
	'linearicons-exit-down',
	'linearicons-exit-left',
	'linearicons-exit-right',
	'linearicons-enter-up2',
	'linearicons-enter-down2',
	'linearicons-enter-vertical',
	'linearicons-enter-left2',
	'linearicons-enter-right2',
	'linearicons-enter-horizontal',
	'linearicons-exit-up2',
	'linearicons-exit-down2',
	'linearicons-exit-left2',
	'linearicons-exit-right2',
	'linearicons-cli',
	'linearicons-bug',
	'linearicons-code',
	'linearicons-file-code',
	'linearicons-file-image',
	'linearicons-file-zip',
	'linearicons-file-audio',
	'linearicons-file-video',
	'linearicons-file-preview',
	'linearicons-file-charts',
	'linearicons-file-stats',
	'linearicons-file-spreadsheet',
	'linearicons-link',
	'linearicons-unlink',
	'linearicons-link2',
	'linearicons-unlink2',
	'linearicons-thumbs-up',
	'linearicons-thumbs-down',
	'linearicons-thumbs-up2',
	'linearicons-thumbs-down2',
	'linearicons-thumbs-up3',
	'linearicons-thumbs-down3',
	'linearicons-share',
	'linearicons-share2',
	'linearicons-share3',
	'linearicons-magnifier',
	'linearicons-file-search',
	'linearicons-find-replace',
	'linearicons-zoom-in',
	'linearicons-zoom-out',
	'linearicons-loupe',
	'linearicons-loupe-zoom-in',
	'linearicons-loupe-zoom-out',
	'linearicons-cross',
	'linearicons-menu',
	'linearicons-list',
	'linearicons-list2',
	'linearicons-list3',
	'linearicons-menu2',
	'linearicons-list4',
	'linearicons-menu3',
	'linearicons-exclamation',
	'linearicons-question',
	'linearicons-check',
	'linearicons-cross2',
	'linearicons-plus',
	'linearicons-minus',
	'linearicons-percent',
	'linearicons-chevron-up',
	'linearicons-chevron-down',
	'linearicons-chevron-left',
	'linearicons-chevron-right',
	'linearicons-chevrons-expand-vertical',
	'linearicons-chevrons-expand-horizontal',
	'linearicons-chevrons-contract-vertical',
	'linearicons-chevrons-contract-horizontal',
	'linearicons-arrow-up',
	'linearicons-arrow-down',
	'linearicons-arrow-left',
	'linearicons-arrow-right',
	'linearicons-arrow-up-right',
	'linearicons-arrows-merge',
	'linearicons-arrows-split',
	'linearicons-arrow-divert',
	'linearicons-arrow-return',
	'linearicons-expand',
	'linearicons-contract',
	'linearicons-expand2',
	'linearicons-contract2',
	'linearicons-move',
	'linearicons-tab',
	'linearicons-arrow-wave',
	'linearicons-expand3',
	'linearicons-expand4',
	'linearicons-contract3',
	'linearicons-notification',
	'linearicons-warning',
	'linearicons-notification-circle',
	'linearicons-question-circle',
	'linearicons-menu-circle',
	'linearicons-checkmark-circle',
	'linearicons-cross-circle',
	'linearicons-plus-circle',
	'linearicons-circle-minus',
	'linearicons-percent-circle',
	'linearicons-arrow-up-circle',
	'linearicons-arrow-down-circle',
	'linearicons-arrow-left-circle',
	'linearicons-arrow-right-circle',
	'linearicons-chevron-up-circle',
	'linearicons-chevron-down-circle',
	'linearicons-chevron-left-circle',
	'linearicons-chevron-right-circle',
	'linearicons-backward-circle',
	'linearicons-first-circle',
	'linearicons-previous-circle',
	'linearicons-stop-circle',
	'linearicons-play-circle',
	'linearicons-pause-circle',
	'linearicons-next-circle',
	'linearicons-last-circle',
	'linearicons-forward-circle',
	'linearicons-eject-circle',
	'linearicons-crop',
	'linearicons-frame-expand',
	'linearicons-frame-contract',
	'linearicons-focus',
	'linearicons-transform',
	'linearicons-grid',
	'linearicons-grid-crossed',
	'linearicons-layers',
	'linearicons-layers-crossed',
	'linearicons-toggle',
	'linearicons-rulers',
	'linearicons-ruler',
	'linearicons-funnel',
	'linearicons-flip-horizontal',
	'linearicons-flip-vertical',
	'linearicons-flip-horizontal2',
	'linearicons-flip-vertical2',
	'linearicons-angle',
	'linearicons-angle2',
	'linearicons-subtract',
	'linearicons-combine',
	'linearicons-intersect',
	'linearicons-exclude',
	'linearicons-align-center-vertical',
	'linearicons-align-right',
	'linearicons-align-bottom',
	'linearicons-align-left',
	'linearicons-align-center-horizontal',
	'linearicons-align-top',
	'linearicons-square',
	'linearicons-plus-square',
	'linearicons-minus-square',
	'linearicons-percent-square',
	'linearicons-arrow-up-square',
	'linearicons-arrow-down-square',
	'linearicons-arrow-left-square',
	'linearicons-arrow-right-square',
	'linearicons-chevron-up-square',
	'linearicons-chevron-down-square',
	'linearicons-chevron-left-square',
	'linearicons-chevron-right-square',
	'linearicons-check-square',
	'linearicons-cross-square',
	'linearicons-menu-square',
	'linearicons-prohibited',
	'linearicons-circle',
	'linearicons-radio-button',
	'linearicons-ligature',
	'linearicons-text-format',
	'linearicons-text-format-remove',
	'linearicons-text-size',
	'linearicons-bold',
	'linearicons-italic',
	'linearicons-underline',
	'linearicons-strikethrough',
	'linearicons-highlight',
	'linearicons-text-align-left',
	'linearicons-text-align-center',
	'linearicons-text-align-right',
	'linearicons-text-align-justify',
	'linearicons-line-spacing',
	'linearicons-indent-increase',
	'linearicons-indent-decrease',
	'linearicons-text-wrap',
	'linearicons-pilcrow',
	'linearicons-direction-ltr',
	'linearicons-direction-rtl',
	'linearicons-page-break',
	'linearicons-page-break2',
	'linearicons-sort-alpha-asc',
	'linearicons-sort-alpha-desc',
	'linearicons-sort-numeric-asc',
	'linearicons-sort-numeric-desc',
	'linearicons-sort-amount-asc',
	'linearicons-sort-amount-desc',
	'linearicons-sort-time-asc',
	'linearicons-sort-time-desc',
	'linearicons-sigma',
	'linearicons-pencil-line',
	'linearicons-hand',
	'linearicons-pointer-up',
	'linearicons-pointer-right',
	'linearicons-pointer-down',
	'linearicons-pointer-left',
	'linearicons-finger-tap',
	'linearicons-fingers-tap',
	'linearicons-reminder',
	'linearicons-fingers-crossed',
	'linearicons-fingers-victory',
	'linearicons-gesture-zoom',
	'linearicons-gesture-pinch',
	'linearicons-fingers-scroll-horizontal',
	'linearicons-fingers-scroll-vertical',
	'linearicons-fingers-scroll-left',
	'linearicons-fingers-scroll-right',
	'linearicons-hand2',
	'linearicons-pointer-up2',
	'linearicons-pointer-right2',
	'linearicons-pointer-down2',
	'linearicons-pointer-left2',
	'linearicons-finger-tap2',
	'linearicons-fingers-tap2',
	'linearicons-reminder2',
	'linearicons-gesture-zoom2',
	'linearicons-gesture-pinch2',
	'linearicons-fingers-scroll-horizontal2',
	'linearicons-fingers-scroll-vertical2',
	'linearicons-fingers-scroll-left2',
	'linearicons-fingers-scroll-right2',
	'linearicons-fingers-scroll-vertical3',
	'linearicons-border-style',
	'linearicons-border-all',
	'linearicons-border-outer',
	'linearicons-border-inner',
	'linearicons-border-top',
	'linearicons-border-horizontal',
	'linearicons-border-bottom',
	'linearicons-border-left',
	'linearicons-border-vertical',
	'linearicons-border-right',
	'linearicons-border-none',
	'linearicons-ellipsis',
	'fa fa fa-500px',
	'fa fa fa-adjust',
	'fa fa fa-adn',
	'fa fa fa-align-center',
	'fa fa fa-align-justify',
	'fa fa fa-align-left',
	'fa fa fa-align-right',
	'fa fa fa-amazon',
	'fa fa fa-ambulance',
	'fa fa fa-anchor',
	'fa fa fa-android',
	'fa fa fa-angellist',
	'fa fa fa-angle-double-down',
	'fa fa fa-angle-double-left',
	'fa fa fa-angle-double-right',
	'fa fa fa-angle-double-up',
	'fa fa fa-angle-down',
	'fa fa fa-angle-left',
	'fa fa fa-angle-right',
	'fa fa fa-angle-up',
	'fa fa fa-apple',
	'fa fa fa-archive',
	'fa fa fa-area-chart',
	'fa fa fa-arrow-circle-down',
	'fa fa fa-arrow-circle-left',
	'fa fa fa-arrow-circle-o-down',
	'fa fa fa-arrow-circle-o-left',
	'fa fa fa-arrow-circle-o-right',
	'fa fa fa-arrow-circle-o-up',
	'fa fa fa-arrow-circle-right',
	'fa fa fa-arrow-circle-up',
	'fa fa fa-arrow-down',
	'fa fa fa-arrow-left',
	'fa fa fa-arrow-right',
	'fa fa fa-arrow-up',
	'fa fa fa-arrows',
	'fa fa fa-arrows-alt',
	'fa fa fa-arrows-h',
	'fa fa fa-arrows-v',
	'fa fa fa-asterisk',
	'fa fa fa-at',
	'fa fa fa-automobile',
	'fa fa fa-backward',
	'fa fa fa-balance-scale',
	'fa fa fa-ban',
	'fa fa fa-bank',
	'fa fa fa-bar-chart',
	'fa fa fa-bar-chart-o',
	'fa fa fa-barcode',
	'fa fa fa-bars',
	'fa fa fa-battery-0',
	'fa fa fa-battery-1',
	'fa fa fa-battery-2',
	'fa fa fa-battery-3',
	'fa fa fa-battery-4',
	'fa fa fa-battery-empty',
	'fa fa fa-battery-full',
	'fa fa fa-battery-half',
	'fa fa fa-battery-quarter',
	'fa fa fa-battery-three-quarters',
	'fa fa fa-bed',
	'fa fa fa-beer',
	'fa fa fa-behance',
	'fa fa fa-behance-square',
	'fa fa fa-bell',
	'fa fa fa-bell-o',
	'fa fa fa-bell-slash',
	'fa fa fa-bell-slash-o',
	'fa fa fa-bicycle',
	'fa fa fa-binoculars',
	'fa fa fa-birthday-cake',
	'fa fa fa-bitbucket',
	'fa fa fa-bitbucket-square',
	'fa fa fa-bitcoin',
	'fa fa fa-black-tie',
	'fa fa fa-bluetooth',
	'fa fa fa-bluetooth-b',
	'fa fa fa-bold',
	'fa fa fa-bolt',
	'fa fa fa-bomb',
	'fa fa fa-book',
	'fa fa fa-bookmark',
	'fa fa fa-bookmark-o',
	'fa fa fa-briefcase',
	'fa fa fa-btc',
	'fa fa fa-bug',
	'fa fa fa-building',
	'fa fa fa-building-o',
	'fa fa fa-bullhorn',
	'fa fa fa-bullseye',
	'fa fa fa-bus',
	'fa fa fa-buysellads',
	'fa fa fa-cab',
	'fa fa fa-calculator',
	'fa fa fa-calendar',
	'fa fa fa-calendar-check-o',
	'fa fa fa-calendar-minus-o',
	'fa fa fa-calendar-o',
	'fa fa fa-calendar-plus-o',
	'fa fa fa-calendar-times-o',
	'fa fa fa-camera',
	'fa fa fa-camera-retro',
	'fa fa fa-car',
	'fa fa fa-caret-down',
	'fa fa fa-caret-left',
	'fa fa fa-caret-right',
	'fa fa fa-caret-square-o-down',
	'fa fa fa-caret-square-o-left',
	'fa fa fa-caret-square-o-right',
	'fa fa fa-caret-square-o-up',
	'fa fa fa-caret-up',
	'fa fa fa-cart-arrow-down',
	'fa fa fa-cart-plus',
	'fa fa fa-cc',
	'fa fa fa-cc-amex',
	'fa fa fa-cc-diners-club',
	'fa fa fa-cc-discover',
	'fa fa fa-cc-jcb',
	'fa fa fa-cc-mastercard',
	'fa fa fa-cc-paypal',
	'fa fa fa-cc-stripe',
	'fa fa fa-cc-visa',
	'fa fa fa-certificate',
	'fa fa fa-chain',
	'fa fa fa-chain-broken',
	'fa fa fa-check',
	'fa fa fa-check-circle',
	'fa fa fa-check-circle-o',
	'fa fa fa-check-square',
	'fa fa fa-check-square-o',
	'fa fa fa-chevron-circle-down',
	'fa fa fa-chevron-circle-left',
	'fa fa fa-chevron-circle-right',
	'fa fa fa-chevron-circle-up',
	'fa fa fa-chevron-down',
	'fa fa fa-chevron-left',
	'fa fa fa-chevron-right',
	'fa fa fa-chevron-up',
	'fa fa fa-child',
	'fa fa fa-chrome',
	'fa fa fa-circle',
	'fa fa fa-circle-o',
	'fa fa fa-circle-o-notch',
	'fa fa fa-circle-thin',
	'fa fa fa-clipboard',
	'fa fa fa-clock-o',
	'fa fa fa-clone',
	'fa fa fa-close',
	'fa fa fa-cloud',
	'fa fa fa-cloud-download',
	'fa fa fa-cloud-upload',
	'fa fa fa-cny',
	'fa fa fa-code',
	'fa fa fa-code-fork',
	'fa fa fa-codepen',
	'fa fa fa-codiepie',
	'fa fa fa-coffee',
	'fa fa fa-cog',
	'fa fa fa-cogs',
	'fa fa fa-columns',
	'fa fa fa-comment',
	'fa fa fa-comment-o',
	'fa fa fa-commenting',
	'fa fa fa-commenting-o',
	'fa fa fa-comments',
	'fa fa fa-comments-o',
	'fa fa fa-compass',
	'fa fa fa-compress',
	'fa fa fa-connectdevelop',
	'fa fa fa-contao',
	'fa fa fa-copy',
	'fa fa fa-copyright',
	'fa fa fa-creative-commons',
	'fa fa fa-credit-card',
	'fa fa fa-credit-card-alt',
	'fa fa fa-crop',
	'fa fa fa-crosshairs',
	'fa fa fa-css3',
	'fa fa fa-cube',
	'fa fa fa-cubes',
	'fa fa fa-cut',
	'fa fa fa-cutlery',
	'fa fa fa-dashboard',
	'fa fa fa-dashcube',
	'fa fa fa-database',
	'fa fa fa-dedent',
	'fa fa fa-delicious',
	'fa fa fa-desktop',
	'fa fa fa-deviantart',
	'fa fa fa-diamond',
	'fa fa fa-digg',
	'fa fa fa-dollar',
	'fa fa fa-dot-circle-o',
	'fa fa fa-download',
	'fa fa fa-dribbble',
	'fa fa fa-dropbox',
	'fa fa fa-drupal',
	'fa fa fa-edge',
	'fa fa fa-edit',
	'fa fa fa-eject',
	'fa fa fa-ellipsis-h',
	'fa fa fa-ellipsis-v',
	'fa fa fa-empire',
	'fa fa fa-envelope',
	'fa fa fa-envelope-o',
	'fa fa fa-envelope-square',
	'fa fa fa-eraser',
	'fa fa fa-eur',
	'fa fa fa-euro',
	'fa fa fa-exchange',
	'fa fa fa-exclamation',
	'fa fa fa-exclamation-circle',
	'fa fa fa-exclamation-triangle',
	'fa fa fa-expand',
	'fa fa fa-expeditedssl',
	'fa fa fa-external-link',
	'fa fa fa-external-link-square',
	'fa fa fa-eye',
	'fa fa fa-eye-slash',
	'fa fa fa-eyedropper',
	'fa fa fa-facebook',
	'fa fa fa-facebook-f',
	'fa fa fa-facebook-official',
	'fa fa fa-facebook-square',
	'fa fa fa-fast-backward',
	'fa fa fa-fast-forward',
	'fa fa fa-fax',
	'fa fa fa-feed',
	'fa fa fa-female',
	'fa fa fa-fighter-jet',
	'fa fa fa-file',
	'fa fa fa-file-archive-o',
	'fa fa fa-file-audio-o',
	'fa fa fa-file-code-o',
	'fa fa fa-file-excel-o',
	'fa fa fa-file-image-o',
	'fa fa fa-file-movie-o',
	'fa fa fa-file-o',
	'fa fa fa-file-pdf-o',
	'fa fa fa-file-photo-o',
	'fa fa fa-file-picture-o',
	'fa fa fa-file-powerpoint-o',
	'fa fa fa-file-sound-o',
	'fa fa fa-file-text',
	'fa fa fa-file-text-o',
	'fa fa fa-file-video-o',
	'fa fa fa-file-word-o',
	'fa fa fa-file-zip-o',
	'fa fa fa-files-o',
	'fa fa fa-film',
	'fa fa fa-filter',
	'fa fa fa-fire',
	'fa fa fa-fire-extinguisher',
	'fa fa fa-firefox',
	'fa fa fa-flag',
	'fa fa fa-flag-checkered',
	'fa fa fa-flag-o',
	'fa fa fa-flash',
	'fa fa fa-flask',
	'fa fa fa-flickr',
	'fa fa fa-floppy-o',
	'fa fa fa-folder',
	'fa fa fa-folder-o',
	'fa fa fa-folder-open',
	'fa fa fa-folder-open-o',
	'fa fa fa-font',
	'fa fa fa-fonticons',
	'fa fa fa-fort-awesome',
	'fa fa fa-forumbee',
	'fa fa fa-forward',
	'fa fa fa-foursquare',
	'fa fa fa-frown-o',
	'fa fa fa-futbol-o',
	'fa fa fa-gamepad',
	'fa fa fa-gavel',
	'fa fa fa-gbp',
	'fa fa fa-ge',
	'fa fa fa-gear',
	'fa fa fa-gears',
	'fa fa fa-genderless',
	'fa fa fa-get-pocket',
	'fa fa fa-gg',
	'fa fa fa-gg-circle',
	'fa fa fa-gift',
	'fa fa-git',
	'fa fa-git-square',
	'fa fa-github',
	'fa fa-github-alt',
	'fa fa-github-square',
	'fa fa-gittip',
	'fa fa-glass',
	'fa fa-globe',
	'fa fa-google',
	'fa fa-google-plus',
	'fa fa-google-plus-square',
	'fa fa-google-wallet',
	'fa fa-graduation-cap',
	'fa fa-gratipay',
	'fa fa-group',
	'fa fa-h-square',
	'fa fa-hacker-news',
	'fa fa-hand-grab-o',
	'fa fa-hand-lizard-o',
	'fa fa-hand-o-down',
	'fa fa-hand-o-left',
	'fa fa-hand-o-right',
	'fa fa-hand-o-up',
	'fa fa-hand-paper-o',
	'fa fa-hand-peace-o',
	'fa fa-hand-pointer-o',
	'fa fa-hand-rock-o',
	'fa fa-hand-scissors-o',
	'fa fa-hand-spock-o',
	'fa fa-hand-stop-o',
	'fa fa-hashtag',
	'fa fa-hdd-o',
	'fa fa-header',
	'fa fa-headphones',
	'fa fa-heart',
	'fa fa-heart-o',
	'fa fa-heartbeat',
	'fa fa-history',
	'fa fa-home',
	'fa fa-hospital-o',
	'fa fa-hotel',
	'fa fa-hourglass',
	'fa fa-hourglass-1',
	'fa fa-hourglass-2',
	'fa fa-hourglass-3',
	'fa fa-hourglass-end',
	'fa fa-hourglass-half',
	'fa fa-hourglass-o',
	'fa fa-hourglass-start',
	'fa fa-houzz',
	'fa fa-html5',
	'fa fa-i-cursor',
	'fa fa-ils',
	'fa fa-image',
	'fa fa-inbox',
	'fa fa-indent',
	'fa fa-industry',
	'fa fa-info',
	'fa fa-info-circle',
	'fa fa-inr',
	'fa fa-instagram',
	'fa fa-institution',
	'fa fa-internet-explorer',
	'fa fa-intersex',
	'fa fa-ioxhost',
	'fa fa-italic',
	'fa fa-joomla',
	'fa fa-jpy',
	'fa fa-jsfiddle',
	'fa fa-key',
	'fa fa-keyboard-o',
	'fa fa-krw',
	'fa fa-language',
	'fa fa-laptop',
	'fa fa-lastfm',
	'fa fa-lastfm-square',
	'fa fa-leaf',
	'fa fa-leanpub',
	'fa fa-legal',
	'fa fa-lemon-o',
	'fa fa-level-down',
	'fa fa-level-up',
	'fa fa-life-bouy',
	'fa fa-life-buoy',
	'fa fa-life-ring',
	'fa fa-life-saver',
	'fa fa-lightbulb-o',
	'fa fa-line-chart',
	'fa fa-link',
	'fa fa-linkedin',
	'fa fa-linkedin-square',
	'fa fa-linux',
	'fa fa-list',
	'fa fa-list-alt',
	'fa fa-list-ol',
	'fa fa-list-ul',
	'fa fa-location-arrow',
	'fa fa-lock',
	'fa fa-long-arrow-down',
	'fa fa-long-arrow-left',
	'fa fa-long-arrow-right',
	'fa fa-long-arrow-up',
	'fa fa-magic',
	'fa fa-magnet',
	'fa fa-mail-forward',
	'fa fa-mail-reply',
	'fa fa-mail-reply-all',
	'fa fa-male',
	'fa fa-map',
	'fa fa-map-marker',
	'fa fa-map-o',
	'fa fa-map-pin',
	'fa fa-map-signs',
	'fa fa-mars',
	'fa fa-mars-double',
	'fa fa-mars-stroke',
	'fa fa-mars-stroke-h',
	'fa fa-mars-stroke-v',
	'fa fa-maxcdn',
	'fa fa-meanpath',
	'fa fa-medium',
	'fa fa-medkit',
	'fa fa-meh-o',
	'fa fa-mercury',
	'fa fa-microphone',
	'fa fa-microphone-slash',
	'fa fa-minus',
	'fa fa-minus-circle',
	'fa fa-minus-square',
	'fa fa-minus-square-o',
	'fa fa-mixcloud',
	'fa fa-mobile',
	'fa fa-mobile-phone',
	'fa fa-modx',
	'fa fa-money',
	'fa fa-moon-o',
	'fa fa-mortar-board',
	'fa fa-motorcycle',
	'fa fa-mouse-pointer',
	'fa fa-music',
	'fa fa-navicon',
	'fa fa-neuter',
	'fa fa-newspaper-o',
	'fa fa-object-group',
	'fa fa-object-ungroup',
	'fa fa-odnoklassniki',
	'fa fa-odnoklassniki-square',
	'fa fa-opencart',
	'fa fa-openid',
	'fa fa-opera',
	'fa fa-optin-monster',
	'fa fa-outdent',
	'fa fa-pagelines',
	'fa fa-paint-brush',
	'fa fa-paper-plane',
	'fa fa-paper-plane-o',
	'fa fa-paperclip',
	'fa fa-paragraph',
	'fa fa-paste',
	'fa fa-pause',
	'fa fa-pause-circle',
	'fa fa-pause-circle-o',
	'fa fa-paw',
	'fa fa-paypal',
	'fa fa-pencil',
	'fa fa-pencil-square',
	'fa fa-pencil-square-o',
	'fa fa-percent',
	'fa fa-phone',
	'fa fa-phone-square',
	'fa fa-photo',
	'fa fa-picture-o',
	'fa fa-pie-chart',
	'fa fa-pied-piper',
	'fa fa-pied-piper-alt',
	'fa fa-pinterest',
	'fa fa-pinterest-p',
	'fa fa-pinterest-square',
	'fa fa-plane',
	'fa fa-play',
	'fa fa-play-circle',
	'fa fa-play-circle-o',
	'fa fa-plug',
	'fa fa-plus',
	'fa fa-plus-circle',
	'fa fa-plus-square',
	'fa fa-plus-square-o',
	'fa fa-power-off',
	'fa fa-print',
	'fa fa-product-hunt',
	'fa fa-puzzle-piece',
	'fa fa-qq',
	'fa fa-qrcode',
	'fa fa-question',
	'fa fa-question-circle',
	'fa fa-quote-left',
	'fa fa-quote-right',
	'fa fa-ra',
	'fa fa-random',
	'fa fa-rebel',
	'fa fa-recycle',
	'fa fa-reddit',
	'fa fa-reddit-alien',
	'fa fa-reddit-square',
	'fa fa-refresh',
	'fa fa-registered',
	'fa fa-remove',
	'fa fa-renren',
	'fa fa-reorder',
	'fa fa-repeat',
	'fa fa-reply',
	'fa fa-reply-all',
	'fa fa-retweet',
	'fa fa-rmb',
	'fa fa-road',
	'fa fa-rocket',
	'fa fa-rotate-left',
	'fa fa-rotate-right',
	'fa fa-rouble',
	'fa fa-rss',
	'fa fa-rss-square',
	'fa fa-rub',
	'fa fa-ruble',
	'fa fa-rupee',
	'fa fa-safari',
	'fa fa-save',
	'fa fa-scissors',
	'fa fa-scribd',
	'fa fa-search',
	'fa fa-search-minus',
	'fa fa-search-plus',
	'fa fa-sellsy',
	'fa fa-send',
	'fa fa-send-o',
	'fa fa-server',
	'fa fa-share',
	'fa fa-share-alt',
	'fa fa-share-alt-square',
	'fa fa-share-square',
	'fa fa-share-square-o',
	'fa fa-shekel',
	'fa fa-sheqel',
	'fa fa-shield',
	'fa fa-ship',
	'fa fa-shirtsinbulk',
	'fa fa-shopping-bag',
	'fa fa-shopping-basket',
	'fa fa-shopping-cart',
	'fa fa-sign-in',
	'fa fa-sign-out',
	'fa fa-signal',
	'fa fa-simplybuilt',
	'fa fa-sitemap',
	'fa fa-skyatlas',
	'fa fa-skype',
	'fa fa-slack',
	'fa fa-sliders',
	'fa fa-slideshare',
	'fa fa-smile-o',
	'fa fa-soccer-ball-o',
	'fa fa-sort',
	'fa fa-sort-alpha-asc',
	'fa fa-sort-alpha-desc',
	'fa fa-sort-amount-asc',
	'fa fa-sort-amount-desc',
	'fa fa-sort-asc',
	'fa fa-sort-desc',
	'fa fa-sort-down',
	'fa fa-sort-numeric-asc',
	'fa fa-sort-numeric-desc',
	'fa fa-sort-up',
	'fa fa-soundcloud',
	'fa fa-space-shuttle',
	'fa fa-spinner',
	'fa fa-spoon',
	'fa fa-spotify',
	'fa fa-square',
	'fa fa-square-o',
	'fa fa-stack-exchange',
	'fa fa-stack-overflow',
	'fa fa-star',
	'fa fa-star-half',
	'fa fa-star-half-empty',
	'fa fa-star-half-full',
	'fa fa-star-half-o',
	'fa fa-star-o',
	'fa fa-steam',
	'fa fa-steam-square',
	'fa fa-step-backward',
	'fa fa-step-forward',
	'fa fa-stethoscope',
	'fa fa-sticky-note',
	'fa fa-sticky-note-o',
	'fa fa-stop',
	'fa fa-stop-circle',
	'fa fa-stop-circle-o',
	'fa fa-street-view',
	'fa fa-strikethrough',
	'fa fa-stumbleupon',
	'fa fa-stumbleupon-circle',
	'fa fa-subscript',
	'fa fa-subway',
	'fa fa-suitcase',
	'fa fa-sun-o',
	'fa fa-superscript',
	'fa fa-support',
	'fa fa-table',
	'fa fa-tablet',
	'fa fa-tachometer',
	'fa fa-tag',
	'fa fa-tags',
	'fa fa-tasks',
	'fa fa-taxi',
	'fa fa-television',
	'fa fa-tencent-weibo',
	'fa fa-terminal',
	'fa fa-text-height',
	'fa fa-text-width',
	'fa fa-th',
	'fa fa-th-large',
	'fa fa-th-list',
	'fa fa-thumb-tack',
	'fa fa-thumbs-down',
	'fa fa-thumbs-o-down',
	'fa fa-thumbs-o-up',
	'fa fa-thumbs-up',
	'fa fa-ticket',
	'fa fa-times',
	'fa fa-times-circle',
	'fa fa-times-circle-o',
	'fa fa-tint',
	'fa fa-toggle-down',
	'fa fa-toggle-left',
	'fa fa-toggle-off',
	'fa fa-toggle-on',
	'fa fa-toggle-right',
	'fa fa-toggle-up',
	'fa fa-trademark',
	'fa fa-train',
	'fa fa-transgender',
	'fa fa-transgender-alt',
	'fa fa-trash',
	'fa fa-trash-o',
	'fa fa-tree',
	'fa fa-trello',
	'fa fa-tripadvisor',
	'fa fa-trophy',
	'fa fa-truck',
	'fa fa-try',
	'fa fa-tty',
	'fa fa-tumblr',
	'fa fa-tumblr-square',
	'fa fa-turkish-lira',
	'fa fa-tv',
	'fa fa-twitch',
	'fa fa-twitter',
	'fa fa-twitter-square',
	'fa fa-umbrella',
	'fa fa-underline',
	'fa fa-undo',
	'fa fa-university',
	'fa fa-unlink',
	'fa fa-unlock',
	'fa fa-unlock-alt',
	'fa fa-unsorted',
	'fa fa-upload',
	'fa fa-usb',
	'fa fa-usd',
	'fa fa-user',
	'fa fa-user-md',
	'fa fa-user-plus',
	'fa fa-user-secret',
	'fa fa-user-times',
	'fa fa-users',
	'fa fa-venus',
	'fa fa-venus-double',
	'fa fa-venus-mars',
	'fa fa-viacoin',
	'fa fa-video-camera',
	'fa fa-vimeo',
	'fa fa-vimeo-square',
	'fa fa-vine',
	'fa fa-vk',
	'fa fa-volume-down',
	'fa fa-volume-off',
	'fa fa-volume-up',
	'fa fa-warning',
	'fa fa-wechat',
	'fa fa-weibo',
	'fa fa-weixin',
	'fa fa-whatsapp',
	'fa fa-wheelchair',
	'fa fa-wifi',
	'fa fa-wikipedia-w',
	'fa fa-windows',
	'fa fa-won',
	'fa fa-wordpress',
	'fa fa-wrench',
	'fa fa-xing',
	'fa fa-xing-square',
	'fa fa-y-combinator',
	'fa fa-y-combinator-square',
	'fa fa-yahoo',
	'fa fa-yc',
	'fa fa-yc-square',
	'fa fa-yelp',
	'fa fa-yen',
	'fa fa-youtube',
	'fa fa-youtube-play',
	'fa fa-youtube-square'
);