 jQuery(document).ready(function(){
	 jQuery('body').append('<div id="quick_view_overlay" style="display:none"></div><div class="AjaxPreloader" style="display:none"></div><div id="quick_view_popup"></div>');
	});
	 function quick_btn(product_id) { 
	  jQuery('#quick_view_overlay').show();
	  jQuery('.AjaxPreloader').show();
					jQuery.ajax({
						url: '?action=test',
						type: 'get',
						data: 'product_id=' + product_id,
						success: function (data) {
                    	jQuery('#quick_view_popup').html(data);
                    jQuery('.AjaxPreloader').hide();
					jQuery('#quick-view').show(500);
					jQuery("#Img_zoom").elevateZoom({
					gallery:'gallery_02' , 
					cursor: 'pointer' , 
					showLens:false,
					zoomType:'lens',
					containLensZoom :false,
					 easing : false, 
					 zoomLens:false,
					 galleryActiveClass: 'zoomThumbActive active'
					 }); 
					 jQuery(".productdetails-view.quick #gallery_02 ul").loveowlCarousel({
						items : 4,
						 itemsDesktop : [1000,3], //5 items between 1000px and 901px
						itemsDesktopSmall : [900,3], // betweem 900px and 601px
						itemsTablet: [700,2], //2 items between 600 and 0
						itemsMobile : [460,2], // itemsMobile disabled - inherit from itemsTablet option
						stopOnHover : true,
						lazyLoad : false,
						pagination : false,
						navigation : true,
						 navigationText: [
						"<i class=\'fa fa-caret-left\'></i>",
						"<i class=\'fa fa-caret-right\'></i>"
						]
						
					}); 
					jQuery('.productdetails-view.quick .vm-chzn-select').chosen();
						RESPONSIVEUIQUICK.responsiveTabsQuick();
						jQuery(function() {
				 			 //jQuery('.product-custom select').styler().trigger('refresh');
						});
					//jQuery('.productdetails-view .addtocart-bar2 .hasTooltip').tooltip();
                    jQuery('#quick-view').css({
                        position: 'fixed',
                    });
					jQuery("#quick_view_popup .productdetails-view.quick").mCustomScrollbar({
						advanced:{
						updateOnContentResize: true
						},
						scrollButtons:{
							enable:true
						}
					});
					var o = jQuery('input[type=radio] , .product-fields input[type=radio]');
					     if (o.length && !jQuery('body').hasClass('.com_config')) {
					        o.each(function () {
					            if (jQuery(this).parent().not('span.radio')) {
					                if (!jQuery(this).attr("id")) {
					                    jQuery(this).attr({id: 'radio' + i}).wrap('<span class="radio"/>').after('<label class="radio_inner" for="radio' + i + '" />')
					                } else {
					                    jQuery(this).wrap('<span class="radio"/>').after('<label class="radio_inner" for="' + jQuery(this).attr("id") + '" />')
					                }
					            }
					        });
					    }
					//accordionShortcod();
					//tabShortcod(
					jQuery("#quick_view_popup .productdetails-view.quick").mCustomScrollbar("update");
			function setproducttype(form, id) {
					form.view = null;
					var datas = form.serialize();
					var prices = form.parents(".productdetails").find(".product-price");
					if (0 == prices.length) {
						prices = jQuery("#productPrice" + id);
					}
					datas = datas.replace("&view=cart", "");

					prices.fadeTo("fast", 0.75);
				    jQuery.ajax({
				        type: "POST",
				        cache: false,
				        dataType: "json",
				        url: window.vmSiteurl + "index.php?&option=com_virtuemart&view=productdetails&task=recalculate&format=json&nosef=1" + window.vmLang,
				        data: datas
				    }).done(
				        function (data, textStatus) {
				            prices.fadeTo("fast", 1);
				            // Remove previous messages generated by this AJAX call:
				            jQuery( "#system-message-container #system-message div.vmprices-message").remove();
				            // refresh price
				            for (var key in data) {
				                var value = data[key];
				                // console.log('my datas',key,value);
				                if ( key=='messages' ) {
				                    // Extract the messages from the returned string, add the vmprices-message class (so the next ajax call
				                    // can remove them again) and then move the messages to the original message container.
				                    // Things are complicated by the fact that no #system-message element exists if no messages were printed so far
				                    var newmessages = jQuery( data[key] ).find("div.alert").addClass("vmprices-message");
				                    if (!jQuery( "#system-message-container #system-message").length && newmessages.length) {
				                        jQuery( "#system-message-container" ).append( "<div id='system-message'></div>" );
				                    }
				                    newmessages.appendTo( "#system-message-container #system-message");
				                } else { // prices
				                    if (value!=0) prices.find("span.Price"+key).show().html(value);
				                    else prices.find(".Price"+key).html(0).hide();
				                }
				            }
				        }
				    );

					return false; // prevent reload
				}
			   function productUpdate() {
				mod=jQuery(".vmCartModule");
				var $ = jQuery ;
				$.ajaxSetup({ cache: false })
				$.getJSON(window.vmSiteurl+"index.php?option=com_virtuemart&nosef=1&view=cart&task=viewJS&format=json"+window.vmLang,
					function(datas, textStatus) {
						if (datas.totalProduct >0) {
							mod.find(".vm_cart_products").html("");
							datas.products.reverse(); 
							$.each(datas.products, function(key, val) {
								if (key<limitcount){								
									$("#hiddencontainer .container").clone().appendTo(".vmCartModule .vm_cart_products");
									$.each(val, function(key, val) {
										if ($("#hiddencontainer .container ."+key)) mod.find(".vm_cart_products ."+key+":last").html(val) ;
									});
									if (key==0) { jQuery("#cart_list div#vm_cart_products").addClass('height').removeClass('heightnone').css('height','auto');}else{jQuery("#cart_list div#vm_cart_products").addClass('heightnone').removeClass('height');}
								}
								
							});
							//alert(datas.products);
							mod.find(".text-art").html(datas.cart_recent_text);
							mod.find(".total").html(datas.billTotal);
							mod.find(".tot3").html(datas.taxTotal);
							mod.find(".tot4").html(datas.discTotal);
							mod.find(".miniart .total2 strong").html(datas.billTotal);
							mod.find(".show_cart").html(datas.cart_show);
							mod.find("#cart_list .vmicon i").html(datas.cart_remove);
							
						}
						mod.find(".total_products").html(datas.totalProductTxt);
						customScrollbar();
					}
				);
					jQuery('body').trigger('updateVirtueMartCartModule');
				}
			function eventsetproducttype(event){
			    Virtuemart.setproducttype(event.data.cart,event.data.virtuemart_product_id);
			}

			 function sendtocart(form){
				if (Virtuemart.addtocart_popup ==1) {
					Virtuemart.cartEffect(form) ;
				} else {
					form.append('<input type="hidden" name="task" value="add" />');
					form.submit();
				}
			}
			function cartEffect(form) {
			    jQuery('.AjaxPreloaderC').show();
				var $ = jQuery ;
				var dat = form.serialize();
			    //jQuery.fancybox.showActivity();
			    jQuery.ajax({
			        type: "POST",
			        cache: false,
			        dataType: "json",
			        url: window.vmSiteurl + "index.php?option=com_virtuemart&nosef=1&view=cart&task=addJS&format=json"+window.vmLang+window.Itemid,
			        data: dat
			    }).done(

				function(datas, textStatus) {
			    jQuery('.AjaxPreloaderC').hide();
					if(datas.stat ==1){
			            var this_prod = form.find(".item_id").val() ;
			            var img_url = document.getElementById('Img_to_Js_'+this_prod).src;
						var txt = datas.msg+"<img width='80' height='auto' src='"+img_url+"' />";
					} else if(datas.stat ==2){
			            var this_prod = form.find(".item_id").val() ;
			            var img_url = document.getElementById('Img_to_Js_'+this_prod).src;
						var txt = datas.msg +"<H4>"+form.find(".pname").val()+"</H4><img width='80' height='auto' src='"+img_url+"' />";
					} else {
						var txt = "<H4>"+vmCartError+"</H4>"+datas.msg;
					}
			            jQuery.fancybox({
								"titlePosition" : 	"inside",
								"transitionIn"	:	"fade",
								"transitionOut"	:	"fade",
								"changeFade"    :   "fast",
								"type"			:	"html",
								"autoCenter"    :   true,
								"closeBtn"      :   true,
								"closeClick"    :   true,
								"content"       :   txt,
								"wrapCSS"    : "fancybox-cart"

							}
						);
					Virtuemart.productUpdate();
				});

			}
			function incrQuantit(event) {
			    var rParent = jQuery(this).parent().parent();
			    quantity = rParent.find('input[name="quantity[]"]');
			    virtuemart_product_id = rParent.find('input[name="virtuemart_product_id[]"]').val();
			    Ste = parseInt(quantity.attr("step"));
			    if (isNaN(Ste)) Ste = 1;
			    Qtt = parseInt(quantity.val());
			    if (!isNaN(Qtt)) {
			        quantity.val(Qtt + Ste);
			        maxQtt = parseInt(quantity.attr("max"));
			        if(!isNaN(maxQtt) && quantity.val()>maxQtt){
			            quantity.val(maxQtt);
			        }
			        Virtuemart.setproducttype(event.data.cart,virtuemart_product_id);
			    }
			};

			function decrQuantity(event) {
			    var rParent = jQuery(this).parent().parent();
			    var quantity = rParent.find('input[name="quantity[]"]');
			    var virtuemart_product_id = rParent.find('input[name="virtuemart_product_id[]"]').val();
			    var Ste = parseInt(quantity.attr("step"));
			    if (isNaN(Ste)) Ste = 1;
			    var minQtt = parseInt(quantity.attr("init"));
			    if (isNaN(minQtt)) minQtt = 1;
			    var Qtt = parseInt(quantity.val());

			    if (!isNaN(Qtt) && Qtt>Ste) {
			        quantity.val(Qtt - Ste);
			        if(!isNaN(minQtt) && quantity.val()<minQtt){
			            quantity.val(minQtt);
			        }
			    } else quantity.val(minQtt);
			    Virtuemart.setproducttype(event.data.cart,virtuemart_product_id);
			};
			function addtocart(e){

		    var targ;
		    if (!e) e = window.event;
		    e.preventDefault();

		    if(e.hasOwnProperty('stopSendtocart') && e.stopSendtocart == true){
		        return false;
		    }
		    if (e.target) targ = e.target;
		    else if (e.srcElement) targ = e.srcElement;
		    if (targ.nodeType == 3) // defeat Safari bug
		        targ = targ.parentNode;

		    if (jQuery(targ).prop("type") == "submit" ||  jQuery(targ).prop("type") == "image" ) {
		        Virtuemart.sendtocart(e.data.cart);
		        return false;
		    }
		};

		function quantityErrorAlert(e) {
			var me = jQuery(this);
			e.preventDefault();
			Virtuemart.checkQuantity(this, me.attr("step"), me.attr("data-errStr"));
		};
			function product(carts) {
	carts.each(function(){
		var cart = jQuery(this),

		quantityInput=cart.find('input[name="quantity[]"]'),
		plus   = cart.find('.quantity-plus'),
		minus  = cart.find('.quantity-minus'),
		select = cart.find('select:not(.no-vm-bind)'),
		radio = cart.find('input:radio:not(.no-vm-bind)'),
		virtuemart_product_id = cart.find('input[name="virtuemart_product_id[]"]').val(),
		quantity = cart.find('.quantity-input');

		var Ste = parseInt(quantityInput.attr("step"));
		//Fallback for layouts lower than 2.0.18b
		if(isNaN(Ste)) { Ste = 1; }


        plus
            .off('click', Virtuemart.incrQuantity)
            .on('click', {cart:cart}, Virtuemart.incrQuantity);

        minus
            .off('click', Virtuemart.decrQuantity)
            .on('click', {cart:cart},Virtuemart.decrQuantity);

        select
            .off('change', Virtuemart.eventsetproducttype)
            .on('change', {cart:cart,virtuemart_product_id:virtuemart_product_id},Virtuemart.eventsetproducttype);

        radio
            .off('change', Virtuemart.eventsetproducttype)
            .on('change', {cart:cart,virtuemart_product_id:virtuemart_product_id},Virtuemart.eventsetproducttype);

        quantity
            .off('click blur submit', Virtuemart.quantityErrorAlert)
            .on('click blur submit', Virtuemart.quantityErrorAlert)
			.off('keyup', Virtuemart.eventsetproducttype)
			.on('keyup', {cart:cart,virtuemart_product_id:virtuemart_product_id},Virtuemart.eventsetproducttype);

        this.action ="#";
        //addtocart = cart.find('input[name="addtocart"]');
        addtocart = cart.find('button.addtocart-button, input[name="addtocart"], a[name="addtocart"]');

        jQuery(addtocart).off('click',Virtuemart.addtocart);
        jQuery(addtocart).on('click',{cart:cart},Virtuemart.addtocart);

	});
}

function checkQuantity (obj,step,myStr) {
    // use the modulus operator "%" to see if there is a remainder
    var remainder=obj.value % step,
        quantity=obj.value;

    if (remainder  != 0) {
        //myStr = "'.vmText::_ ('COM_VIRTUEMART_WRONG_AMOUNT_ADDED').'";
        alert(myStr.replace("%s",step));
        if(quantity!=remainder && quantity>remainder){
            obj.value = quantity-remainder;
        } else {
            obj.value = step;
        }
        return false;
    }
    return true;
}	
	product(jQuery(".product"));
	jQuery("form.js-recalculate").each(function(){
		if (jQuery(this).find(".product-fields").length) {
			var id= jQuery(this).find('input[name="virtuemart_product_id[]"]').val();
			setproducttype(jQuery(this),id);

		}
	});
                    jQuery('#quick_view_overlay, #quick_view_close').click(function () {
                        jQuery('#quick-view').remove();
                        jQuery('#quick_view_overlay').hide();
						//jQuery('.AjaxPreloader').hide();
                    });
					jQuery(document).keyup(function(e) {
					  if (e.keyCode == 27) { jQuery('#quick_view_close').click(); }   // esc
					});
                    return false;
                }
					});
				}
jQuery(document).ready(function(){				
	jQuery('.productdetails-view.quick .product-field-type-A select').live('change', function(ev) {
	console.log('change');															   
	  var url =  this.value;
	   	//var start = url.indexOf("virtuemart_product_id=");
		//alert(url);
		//var finish = url.indexOf("&", start);
		//alert(finish);
		//var fin = '' + finish;
		//var res = url.substr(145, 2);
		//alert(res);
		jQuery.ajax({
			url: '?action=test',
			type: 'get',
			data: 'product_id=' + url,
			success: function (data) {
				jQuery('#quick_view_popup').html(data);
			jQuery("#Img_zoom").elevateZoom({
					gallery:'gallery_02' , 
					cursor: 'pointer' , 
					showLens:false,
					zoomType:'lens',
					containLensZoom :false,
					 easing : false, 
					 zoomLens:false,
					 galleryActiveClass: 'zoomThumbActive active'
					 }); 
					 jQuery(".productdetails-view.quick #gallery_02 ul").owlCarousel({
						items : 4,
						 itemsDesktop : [1000,3], //5 items between 1000px and 901px
						itemsDesktopSmall : [900,3], // betweem 900px and 601px
						itemsTablet: [700,2], //2 items between 600 and 0
						itemsMobile : [460,2], // itemsMobile disabled - inherit from itemsTablet option
						stopOnHover : true,
						lazyLoad : false,
						pagination : false,
						navigation : true,
						 navigationText: [
						"<i class=\'fa fa-caret-left\'></i>",
						"<i class=\'fa fa-caret-right\'></i>"
						]
						
					}); 
					jQuery('.productdetails-view.quick .vm-chzn-select').chosen();
						RESPONSIVEUIQUICK.responsiveTabsQuick();
                    jQuery('#quick-view').css({
                        position: 'fixed',
                    });
					jQuery("#quick_view_popup .productdetails-view.quick").mCustomScrollbar({
						advanced:{
						updateOnContentResize: true
						},
						scrollButtons:{
							enable:true
						}
					});
					jQuery("#quick_view_popup .productdetails-view.quick").mCustomScrollbar("update");
					function setproducttype(form, id) {
					form.view = null;
					var datas = form.serialize();
					var prices = form.parents(".productdetails").find(".product-price");
					if (0 == prices.length) {
						prices = jQuery("#productPrice" + id);
					}
					datas = datas.replace("&view=cart", "");

					prices.fadeTo("fast", 0.75);
				    jQuery.ajax({
				        type: "POST",
				        cache: false,
				        dataType: "json",
				        url: window.vmSiteurl + "index.php?&option=com_virtuemart&view=productdetails&task=recalculate&format=json&nosef=1" + window.vmLang,
				        data: datas
				    }).done(
				        function (data, textStatus) {
				            prices.fadeTo("fast", 1);
				            // Remove previous messages generated by this AJAX call:
				            jQuery( "#system-message-container #system-message div.vmprices-message").remove();
				            // refresh price
				            for (var key in data) {
				                var value = data[key];
				                // console.log('my datas',key,value);
				                if ( key=='messages' ) {
				                    // Extract the messages from the returned string, add the vmprices-message class (so the next ajax call
				                    // can remove them again) and then move the messages to the original message container.
				                    // Things are complicated by the fact that no #system-message element exists if no messages were printed so far
				                    var newmessages = jQuery( data[key] ).find("div.alert").addClass("vmprices-message");
				                    if (!jQuery( "#system-message-container #system-message").length && newmessages.length) {
				                        jQuery( "#system-message-container" ).append( "<div id='system-message'></div>" );
				                    }
				                    newmessages.appendTo( "#system-message-container #system-message");
				                } else { // prices
				                    if (value!=0) prices.find("span.Price"+key).show().html(value);
				                    else prices.find(".Price"+key).html(0).hide();
				                }
				            }
				        }
				    );

					return false; // prevent reload
				}
			   function productUpdate() {
				mod=jQuery(".vmCartModule");
				var $ = jQuery ;
				$.ajaxSetup({ cache: false })
				$.getJSON(window.vmSiteurl+"index.php?option=com_virtuemart&nosef=1&view=cart&task=viewJS&format=json"+window.vmLang,
					function(datas, textStatus) {
						if (datas.totalProduct >0) {
							mod.find(".vm_cart_products").html("");
							datas.products.reverse(); 
							$.each(datas.products, function(key, val) {
								if (key<limitcount){								
									$("#hiddencontainer .container").clone().appendTo(".vmCartModule .vm_cart_products");
									$.each(val, function(key, val) {
										if ($("#hiddencontainer .container ."+key)) mod.find(".vm_cart_products ."+key+":last").html(val) ;
									});
									if (key==0) { jQuery("#cart_list div#vm_cart_products").addClass('height').removeClass('heightnone').css('height','auto');}else{jQuery("#cart_list div#vm_cart_products").addClass('heightnone').removeClass('height');}
								}
								
							});
							//alert(datas.products);
							mod.find(".text-art").html(datas.cart_recent_text);
							mod.find(".total").html(datas.billTotal);
							mod.find(".tot3").html(datas.taxTotal);
							mod.find(".tot4").html(datas.discTotal);
							mod.find(".miniart .total2 strong").html(datas.billTotal);
							mod.find(".show_cart").html(datas.cart_show);
							mod.find("#cart_list .vmicon i").html(datas.cart_remove);
							
						}
						mod.find(".total_products").html(datas.totalProductTxt);
						customScrollbar();
					}
				);
					jQuery('body').trigger('updateVirtueMartCartModule');
				}
			function eventsetproducttype(event){
			    Virtuemart.setproducttype(event.data.cart,event.data.virtuemart_product_id);
			}

			 function sendtocart(form){
				if (Virtuemart.addtocart_popup ==1) {
					Virtuemart.cartEffect(form) ;
				} else {
					form.append('<input type="hidden" name="task" value="add" />');
					form.submit();
				}
			}
			function cartEffect(form) {
			    jQuery('.AjaxPreloaderC').show();
				var $ = jQuery ;
				var dat = form.serialize();
			    //jQuery.fancybox.showActivity();
			    jQuery.ajax({
			        type: "POST",
			        cache: false,
			        dataType: "json",
			        url: window.vmSiteurl + "index.php?option=com_virtuemart&nosef=1&view=cart&task=addJS&format=json"+window.vmLang+window.Itemid,
			        data: dat
			    }).done(

				function(datas, textStatus) {
			    jQuery('.AjaxPreloaderC').hide();
					if(datas.stat ==1){
			            var this_prod = form.find(".item_id").val() ;
			            var img_url = document.getElementById('Img_to_Js_'+this_prod).src;
						var txt = datas.msg+"<img width='80' height='auto' src='"+img_url+"' />";
					} else if(datas.stat ==2){
			            var this_prod = form.find(".item_id").val() ;
			            var img_url = document.getElementById('Img_to_Js_'+this_prod).src;
						var txt = datas.msg +"<H4>"+form.find(".pname").val()+"</H4><img width='80' height='auto' src='"+img_url+"' />";
					} else {
						var txt = "<H4>"+vmCartError+"</H4>"+datas.msg;
					}
			            jQuery.fancybox({
								"titlePosition" : 	"inside",
								"transitionIn"	:	"fade",
								"transitionOut"	:	"fade",
								"changeFade"    :   "fast",
								"type"			:	"html",
								"autoCenter"    :   true,
								"closeBtn"      :   true,
								"closeClick"    :   true,
								"content"       :   txt,
								"wrapCSS"    : "fancybox-cart"
							}
						);
					Virtuemart.productUpdate();
				});

			}
			function incrQuantit(event) {
			    var rParent = jQuery(this).parent().parent();
			    quantity = rParent.find('input[name="quantity[]"]');
			    virtuemart_product_id = rParent.find('input[name="virtuemart_product_id[]"]').val();
			    Ste = parseInt(quantity.attr("step"));
			    if (isNaN(Ste)) Ste = 1;
			    Qtt = parseInt(quantity.val());
			    if (!isNaN(Qtt)) {
			        quantity.val(Qtt + Ste);
			        maxQtt = parseInt(quantity.attr("max"));
			        if(!isNaN(maxQtt) && quantity.val()>maxQtt){
			            quantity.val(maxQtt);
			        }
			        Virtuemart.setproducttype(event.data.cart,virtuemart_product_id);
			    }
			};

			function decrQuantity(event) {
			    var rParent = jQuery(this).parent().parent();
			    var quantity = rParent.find('input[name="quantity[]"]');
			    var virtuemart_product_id = rParent.find('input[name="virtuemart_product_id[]"]').val();
			    var Ste = parseInt(quantity.attr("step"));
			    if (isNaN(Ste)) Ste = 1;
			    var minQtt = parseInt(quantity.attr("init"));
			    if (isNaN(minQtt)) minQtt = 1;
			    var Qtt = parseInt(quantity.val());

			    if (!isNaN(Qtt) && Qtt>Ste) {
			        quantity.val(Qtt - Ste);
			        if(!isNaN(minQtt) && quantity.val()<minQtt){
			            quantity.val(minQtt);
			        }
			    } else quantity.val(minQtt);
			    Virtuemart.setproducttype(event.data.cart,virtuemart_product_id);
			};
			function addtocart(e){

		    var targ;
		    if (!e) e = window.event;
		    e.preventDefault();

		    if(e.hasOwnProperty('stopSendtocart') && e.stopSendtocart == true){
		        return false;
		    }
		    if (e.target) targ = e.target;
		    else if (e.srcElement) targ = e.srcElement;
		    if (targ.nodeType == 3) // defeat Safari bug
		        targ = targ.parentNode;

		    if (jQuery(targ).prop("type") == "submit" ||  jQuery(targ).prop("type") == "image" ) {
		        Virtuemart.sendtocart(e.data.cart);
		        return false;
		    }
		};

		function quantityErrorAlert(e) {
			var me = jQuery(this);
			e.preventDefault();
			Virtuemart.checkQuantity(this, me.attr("step"), me.attr("data-errStr"));
		};
			function product(carts) {
	carts.each(function(){
		var cart = jQuery(this),

		quantityInput=cart.find('input[name="quantity[]"]'),
		plus   = cart.find('.quantity-plus'),
		minus  = cart.find('.quantity-minus'),
		select = cart.find('select:not(.no-vm-bind)'),
		radio = cart.find('input:radio:not(.no-vm-bind)'),
		virtuemart_product_id = cart.find('input[name="virtuemart_product_id[]"]').val(),
		quantity = cart.find('.quantity-input');

		var Ste = parseInt(quantityInput.attr("step"));
		//Fallback for layouts lower than 2.0.18b
		if(isNaN(Ste)) { Ste = 1; }


        plus
            .off('click', Virtuemart.incrQuantity)
            .on('click', {cart:cart}, Virtuemart.incrQuantity);

        minus
            .off('click', Virtuemart.decrQuantity)
            .on('click', {cart:cart},Virtuemart.decrQuantity);

        select
            .off('change', Virtuemart.eventsetproducttype)
            .on('change', {cart:cart,virtuemart_product_id:virtuemart_product_id},Virtuemart.eventsetproducttype);

        radio
            .off('change', Virtuemart.eventsetproducttype)
            .on('change', {cart:cart,virtuemart_product_id:virtuemart_product_id},Virtuemart.eventsetproducttype);

        quantity
            .off('click blur submit', Virtuemart.quantityErrorAlert)
            .on('click blur submit', Virtuemart.quantityErrorAlert)
			.off('keyup', Virtuemart.eventsetproducttype)
			.on('keyup', {cart:cart,virtuemart_product_id:virtuemart_product_id},Virtuemart.eventsetproducttype);

        this.action ="#";
        //addtocart = cart.find('input[name="addtocart"]');
        addtocart = cart.find('button.addtocart-button, input[name="addtocart"], a[name="addtocart"]');

        jQuery(addtocart).off('click',Virtuemart.addtocart);
        jQuery(addtocart).on('click',{cart:cart},Virtuemart.addtocart);

	});
}

function checkQuantity (obj,step,myStr) {
    // use the modulus operator "%" to see if there is a remainder
    var remainder=obj.value % step,
        quantity=obj.value;

    if (remainder  != 0) {
        //myStr = "'.vmText::_ ('COM_VIRTUEMART_WRONG_AMOUNT_ADDED').'";
        alert(myStr.replace("%s",step));
        if(quantity!=remainder && quantity>remainder){
            obj.value = quantity-remainder;
        } else {
            obj.value = step;
        }
        return false;
    }
    return true;
}		
			product(jQuery(".product"));
			jQuery("form.js-recalculate").each(function(){
				if (jQuery(this).find(".product-fields").length) {
					var id= jQuery(this).find('input[name="virtuemart_product_id[]"]').val();
					setproducttype(jQuery(this),id);
		
				}
			});
			jQuery('#quick_view_overlay, #quick_view_close').click(function () {
                        jQuery('#quick-view').remove();
                        jQuery('#quick_view_overlay').hide();
						//jQuery('.AjaxPreloader').hide();
                    });
					jQuery(document).keyup(function(e) {
					  if (e.keyCode == 27) { jQuery('#quick_view_close').click(); }   // esc
					});
			}
		});
		
		return false;
	});
});				
